# Bugfix Workflow
# バグ修正ワークフロー

name: bugfix
description: "バグ修正の標準ワークフロー"

trigger:
  - "bugfix/* ブランチ作成"
  - "バグ報告"

steps:
  - id: 0
    name: "要件・仕様との紐付け"
    agent: architect
    description: |
      バグがどの要件・仕様に関連するかを特定する。
      トレーサビリティを確保し、再発防止に繋げる。
    action: |
      - バグが影響する要件を特定（docs/requirements/）
      - 関連する詳細仕様を特定（docs/design/specs/）
      - 仕様の不備が原因か、実装の不備が原因かを判断
    output:
      - 関連要件・仕様へのリンク
      - 原因区分（仕様不備 / 実装不備 / 想定外ケース）
    next: 1

  - id: 1
    name: "バグ分析"
    agent: architect
    action: |
      - バグの再現手順確認
      - 原因の特定
      - 影響範囲の分析
    output:
      - 原因分析レポート
      - 修正方針
    next: 2

  - id: 2
    name: "修正実装"
    agent: implementer
    action: |
      - バグ修正コード実装
      - 回帰テスト作成
    output:
      - 修正コード
      - 回帰テスト
    next: 3

  - id: 3
    name: "レビュー"
    agent: reviewer
    action: |
      - 修正内容のレビュー
      - 副作用の確認
    output:
      - レビューコメント
    decision:
      approved: 4
      rejected: 2

  - id: 4
    name: "テスト実行"
    agent: tester
    action: |
      - 回帰テスト実行
      - 既存テスト実行
    output:
      - テスト結果
    decision:
      passed: 5
      failed: 2

  - id: 5
    name: "PR作成・人間承認"
    agent: human
    action: |
      - PR確認
      - 承認
    output:
      - 承認/却下
    decision:
      approved: "DONE"
      feedback: 2
