# Feature Development Workflow
# 機能開発ワークフロー（並列サブエージェント対応）

name: feature-development
version: "2.0"  # 並列サブエージェント導入
description: "新機能開発の標準ワークフロー"

trigger:
  - "feature/* ブランチ作成"
  - "人間からの機能開発指示"

# =============================================================================
# ワークフローステップ
# =============================================================================
steps:
  # -------------------------------------------------------------------------
  # Step 0: 要件定義（Requirements Analyst）
  # -------------------------------------------------------------------------
  - id: 0
    name: "要件定義（Requirements Analyst）"
    description: |
      **Humanの原体験・ビジョンを構造化された要件に変換**
      Human主体でAIがサポート。推測で要件を追加しない。

      このステップがないと、Architectが「何を作るべきか」を推測してしまう。
      要件定義フェーズでHumanの意図を明確化することで、
      設計・実装の品質が大幅に向上する。

    agent: requirements_analyst
    mode: human_led  # Human主体、AI補助

    action: |
      ## 1. ビジョン・ゴールのヒアリング
      - Humanから原体験・課題意識を聞き取る
      - 「なぜ作るのか」を明文化
      - 成功指標を定義

      ## 2. ユーザーストーリーの作成
      - As a / I want / So that 形式
      - 受け入れ条件を定義
      - MoSCoW優先度付け（Human決定）

      ## 3. 機能要件の整理
      - 各ストーリーから機能要件を抽出
      - ビジョン・ゴールとの紐付けを維持

      ## 4. 要件の承認
      - 全要件をHumanに提示
      - 承認を得てから次のステップへ

    human_confirmation:
      required_for:
        - ビジョン・ゴールの確定
        - ユーザーストーリーの優先度
        - 機能要件の最終承認
      note: "要件はHumanが決める。AIは整理・構造化を補助するのみ。"

    output:
      - docs/requirements/vision.md
      - docs/requirements/user-stories/*.md
      - docs/requirements/features/*.md

    next: 1

  # -------------------------------------------------------------------------
  # Step 1: 並列設計（サブエージェント）
  # -------------------------------------------------------------------------
  - id: 1
    name: "並列設計（Plan Subagents）"
    description: |
      大規模タスクでは複数のPlanサブエージェントを並列実行。
      各ドメイン専門家が独立して設計し、Architectが統合する。
      参考: @cloudxdev "Multiple Plan subagents always yields a better result"

    parallel_agents:
      - agent: subagents/backend_planner
        focus: "API設計、サービス層、外部連携"
        output: "backend_design.yml"

      - agent: subagents/mobile_planner
        focus: "モバイル設計、UI/UX、オンデバイス処理"
        output: "mobile_design.yml"

      - agent: subagents/infra_planner
        focus: "Docker、CI/CD、環境構築"
        output: "infra_design.yml"

    aggregator:
      agent: architect
      action: |
        - サブエージェント出力を統合
        - 矛盾点・ギャップを解消
        - 統合設計書を作成
        - タスクに分解
        - 必要に応じてADR作成
      output:
        - 統合設計書
        - タスクリスト
        - ADR（必要な場合）
    next: 2

  # -------------------------------------------------------------------------
  # Step 2: 仕様詳細化（Spec Writer）
  # -------------------------------------------------------------------------
  - id: 2
    name: "仕様詳細化"
    agent: spec_writer  # Opus必須
    description: |
      **基本設計から詳細仕様を作成**
      実装者が迷わないレベルまで仕様を詳細化する。
      ビジネス判断・ユーザー体験に関わる部分は必ずHumanに確認。

    action: |
      ## 1. 基本設計の読み込み
      - Architectの統合設計書からタスクごとの基本仕様を抽出

      ## 2. 詳細仕様のチェック（チェックリスト使用）
      以下の項目を全て定義する：
      - [ ] 入力: データ型、バリデーションルール、境界値
      - [ ] 出力: 正常系レスポンス、異常系レスポンス
      - [ ] エッジケース: null、空文字、最大値、最小値、タイムアウト
      - [ ] エラーハンドリング: どのエラーをどう処理するか
      - [ ] 状態遷移: 状態がある場合、全遷移パターン

      ## 3. 曖昧さの解消
      - 技術的詳細 → 自分で補完（根拠を明記）
      - ビジネス判断 → **Humanに確認**（推測しない）
      - ユーザー体験 → **Humanに確認**（推測しない）

      ## 4. テストケースの定義
      - Given-When-Then形式で全ケースを列挙
      - 正常系・異常系・エッジケースを網羅

    human_confirmation:
      required_for:
        - ユーザー体験に関わる仕様
        - ビジネスロジック・ビジネスルール
        - 優先度・トレードオフの判断

    output:
      - 詳細仕様書
      - テストケース定義（Given-When-Then）
      - Human確認記録
    next: 3

  # -------------------------------------------------------------------------
  # Step 3: 設計レビュー（基本設計 + 詳細仕様をまとめてレビュー）
  # -------------------------------------------------------------------------
  - id: 3
    name: "設計レビュー"
    agent: reviewer
    description: |
      **基本設計と詳細仕様を統合的にレビュー**
      詳細仕様が完成した状態でレビューすることで、
      実装前に問題を発見できる。
    action: |
      - Architectの基本設計をレビュー
      - Spec Writerの詳細仕様をレビュー
      - 各サブエージェント設計の整合性確認
      - 詳細仕様の実装可能性を評価
      - 懸念点・改善提案を提示
      - Orchestration Guardian チェック
    output:
      - レビューコメント
    decision:
      approved: 4
      spec_issues: 2  # 詳細仕様の修正が必要
      design_issues: 1  # 基本設計からやり直し

  # -------------------------------------------------------------------------
  # Step 4: TDD実装（テスト先行）
  # -------------------------------------------------------------------------
  - id: 4
    name: "TDD実装"
    agent: implementer
    description: |
      **TDD（テスト駆動開発）を厳守**
      Spec Writerが作成した詳細仕様に基づき実装する。
      仕様に不明点があればSpec Writerに差し戻す（自分で補完しない）。

      1. 詳細仕様のテストケースをコードに落とす
      2. テストを実行（この時点では失敗する）
      3. テストがパスする最小限のコードを実装
      4. リファクタリング
      5. 全テストがパスするまで繰り返し

    tdd_process:
      - step: "Verify Spec"
        description: "詳細仕様の確認（Spec Writerが作成済み）"
        action: |
          ## Spec Writerの詳細仕様を確認
          - 詳細仕様書を読み込む
          - テストケース定義（Given-When-Then）を確認
          - 不明点・曖昧な点がないか確認

          ## 不明点がある場合
          - **自分で補完しない**
          - **Spec Writerに差し戻す**

        checkpoint:
          clear: "Redへ進む"
          unclear: "Spec Writer（Step 2）に差し戻し"

      - step: "Red"
        action: "明確化した仕様からテストコードを作成（失敗するテスト）"
        output: "tests/"

      - step: "Green"
        action: "テストがパスする最小限の実装"
        output: "src/"

      - step: "Refactor"
        action: "コード品質を改善（テストは維持）"
        output: "src/"

    constraints:
      - "仕様が不明確なまま実装を始めない（Specステップ必須）"
      - "テストコードを先に書く（実装より前）"
      - "テストがパスするまで次のタスクに進まない"
      - "曖昧な仕様は推測せずHumanに確認する"

    output:
      - テストコード
      - プロダクションコード
    next: 5

  # -------------------------------------------------------------------------
  # Step 5: コードレビュー
  # -------------------------------------------------------------------------
  - id: 5
    name: "コードレビュー"
    agent: reviewer
    action: |
      - 実装コードをレビュー
      - TDDプロセス遵守を確認
      - 品質・セキュリティチェック
    output:
      - レビューコメント
    decision:
      approved: 6
      minor_issues: 4.5  # 軽微な修正
      rejected: 4  # 実装やり直し

  # -------------------------------------------------------------------------
  # Step 4.5: 軽微な修正
  # -------------------------------------------------------------------------
  - id: 4.5
    name: "軽微な修正"
    agent: implementer
    action: |
      - レビューコメントに基づき修正
      - テストが引き続きパスすることを確認
    output:
      - 修正済みコード
    next: 6

  # -------------------------------------------------------------------------
  # Step 6: テスト実行・検証
  # -------------------------------------------------------------------------
  - id: 6
    name: "テスト実行"
    agent: tester
    action: |
      - 全テスト実行
      - カバレッジ確認（目標: 80%以上）
      - エッジケースの追加検討
    output:
      - テスト結果
      - カバレッジレポート
    decision:
      passed: 7
      failed: 4  # 実装修正

  # -------------------------------------------------------------------------
  # Step 7: PR作成
  # -------------------------------------------------------------------------
  - id: 7
    name: "PR作成"
    agent: implementer
    action: |
      - Pull Request作成
      - 変更内容のサマリー作成
      - テスト結果・カバレッジを記載
    output:
      - PR
    next: 8

  # -------------------------------------------------------------------------
  # Step 8: Human Checkpoint
  # -------------------------------------------------------------------------
  - id: 8
    name: "人間による最終承認"
    agent: human
    action: |
      - PRをレビュー
      - 承認またはフィードバック
    output:
      - 承認/却下
    decision:
      approved: "DONE"
      feedback: 4  # 追加修正

# =============================================================================
# TDDルール（明文化）
# =============================================================================
tdd_rules:
  principle: "Spec Writerが詳細仕様を作成し、Implementerはその仕様に従って実装する"

  roles:
    spec_writer:
      responsibility: "詳細仕様の作成、Human確認"
      model: opus
    implementer:
      responsibility: "詳細仕様に基づくTDD実装（仕様は作らない）"
      model: sonnet

  workflow:
    0_spec_detail: |
      【Spec Writer（Opus）の責務】
      チェックリスト使用: .ai/templates/spec-detail-checklist.md

      ## 基本仕様の確認
      - 設計書から該当タスクの仕様を抽出
      - 「何を作るか」が明確か確認
      - 不明確な場合 → 設計フェーズに差し戻し

      ## 詳細仕様の作成
      - 入力: データ型、バリデーション、境界値
      - 出力: 正常系、異常系
      - エッジケース: null、空、最大最小、タイムアウト
      - エラーハンドリング: 各エラーの処理方法
      - 状態遷移: 全パターン（該当する場合）

      ## Human確認（必須）
      - ビジネス判断 → Humanに確認
      - ユーザー体験 → Humanに確認
      - 推測で進めない

      ## テストケース定義
      - Given-When-Then形式で全ケースを列挙

    1_verify_spec: |
      【Implementer（Sonnet）の責務】
      - Spec Writerの詳細仕様を確認
      - 不明点があればSpec Writerに差し戻し（自分で補完しない）

    2_write_test: "詳細仕様のテストケースをコードに落とす"
    2_run_test: "テスト実行（RED: 失敗することを確認）"
    3_implement: "テストがパスする最小限のコードを実装"
    4_run_test: "テスト実行（GREEN: パスすることを確認）"
    5_refactor: "コード品質改善（テストは維持）"
    6_repeat: "全テストがパスするまで繰り返し"

  constraints:
    - "仕様が不明確なまま実装を始めない"
    - "曖昧な仕様は推測せずHumanに確認する"
    - "実装コードを書く前に必ずテストを書く"
    - "テストが失敗する状態（RED）を確認してから実装"
    - "テストがパスしないまま次のタスクに進まない"
    - "リファクタリング後も全テストがパスすること"

  coverage_target:
    minimum: 80%
    ideal: 90%

# =============================================================================
# アウトプット保存ルール（必須）
# =============================================================================
output_preservation:
  principle: "全てのアウトプットはドキュメントとして保存する"

  rules:
    - "会話内で完結させず、必ずファイルに保存する"
    - "レビュー結果、設計、仕様、議事録など全て対象"
    - "保存先は内容に応じて適切なディレクトリを選択"

  output_locations:
    specs: "docs/design/specs/"           # 詳細仕様書
    reviews: "docs/design/reviews/"       # レビュー結果
    decisions: "docs/design/decisions/"   # 設計判断（ADR）
    meetings: "docs/journal/meetings/"    # 議事録・確認記録

  required_outputs_by_step:
    step_1_design:
      - "統合設計書 → docs/design/"
      - "タスクリスト → docs/design/"
    step_2_spec:
      - "詳細仕様書 → docs/design/specs/"
      - "Human確認記録 → 仕様書内に記載"
    step_3_review:
      - "レビュー結果 → docs/design/reviews/"
      - "指摘事項と判定 → レビュー結果内に記載"
    step_4_implement:
      - "テストコード → tests/"
      - "プロダクションコード → src/"
    step_5_code_review:
      - "コードレビュー結果 → PRコメントまたはdocs/"

  enforcement:
    - "各ステップ完了時にアウトプットファイルの存在を確認"
    - "保存されていない場合はステップ完了とみなさない"
